##### Load Packages ############################################################
# install.packages('xts')
# install.packages('ggplot2')
# install.packages('ggfortify')
# install.packages('forecast')
# install.packages('scales')
# install.packages('dplyr')
# install.packages('ggthemes')
# install.packages('tidyr')
# install.packages('tbl2xts')
# install.packages('xtable')
# install.packages('moments')
# install.packages('qqplotr')
# install.packages('lmtest')
# install.packages('car')
# install.packages('tseries')
# install.packages('rugarch')
# install.packages('broom')
# install.packages('TSA')
# install.packages('ggseas')
# install.packages('aTSA')
# install.packages('PerformanceAnalytics')
# install.packages('lmtest')

# Load my functions
source('Dissertation/Prep/Functions.R')

library(xts)
library(ggplot2)
library(ggfortify)
library(forecast)
library(scales)
library(dplyr)
library(ggthemes)
library(tidyr)
library(tbl2xts)
library(xtable)
library(moments)
library(qqplotr)
library(lmtest)
library(car)
library(tseries)
library(rugarch)
library(broom)
library(TSA)
library(ggseas)
library(aTSA)
library(PerformanceAnalytics)
library(lmtest)
